CREATE TABLE [dbo].[Patches] (
    [ID]                     INT            NOT NULL,
    [CameraName]             NVARCHAR(50)   NOT NULL,
    [Polygon_ID]             INT            NOT NULL,
    [BlueHistogram]          NVARCHAR (MAX) NULL,
    [GreenHistogram]         NVARCHAR (MAX) NULL,
    [RedHistogram]           NVARCHAR (MAX) NULL,
    [ModeBlue]               FLOAT (53)     NULL,
    [ModeGreen]              FLOAT (53)     NULL,
    [ModeRed]                FLOAT (53)     NULL,
    [MeanBlue]               FLOAT (53)     NULL,
    [MeanGreen]              FLOAT (53)     NULL,
    [MeanRed]                FLOAT (53)     NULL,
    [MedianBlue]             FLOAT (53)     NULL,
    [MedianGreen]            FLOAT (53)     NULL,
    [MedianRed]              FLOAT (53)     NULL,
    [MinimumBlue]            FLOAT (53)     NULL,
    [MinimumGreen]           FLOAT (53)     NULL,
    [MinimumRed]             FLOAT (53)     NULL,
    [MaximumBlue]            FLOAT (53)     NULL,
    [MaximumGreen]           FLOAT (53)     NULL,
    [MaximumRed]             FLOAT (53)     NULL,
    [StandardDeviationBlue]  FLOAT (53)     NULL,
    [StandardDeviationGreen] FLOAT (53)     NULL,
    [StandardDeviationRed]   FLOAT (53)     NULL,
    [VarianceBlue]           FLOAT (53)     NULL,
    [VarianceGreen]          FLOAT (53)     NULL,
    [VarianceRed]            FLOAT (53)     NULL,
    [ContrastBlue]           FLOAT (53)     NULL,
    [ContrastGreen]          FLOAT (53)     NULL,
    [ContrastRed]            FLOAT (53)     NULL,
    [Snow]         BIT           NULL,
    [NoSnow]       BIT           NULL,
    [Foggy]        BIT           NULL,
    [Rainy]        BIT           NULL,
    [BadLighting]  BIT           NULL,
    [GoodLighting] BIT           NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);

