#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schneedetektion.Data
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="StrassenbilderMeta")]
	public partial class StrassenbilderMetaDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCamera(Camera instance);
    partial void UpdateCamera(Camera instance);
    partial void DeleteCamera(Camera instance);
    partial void InsertPolygon(Polygon instance);
    partial void UpdatePolygon(Polygon instance);
    partial void DeletePolygon(Polygon instance);
    partial void InsertImage(Image instance);
    partial void UpdateImage(Image instance);
    partial void DeleteImage(Image instance);
    partial void InsertPatch(Patch instance);
    partial void UpdatePatch(Patch instance);
    partial void DeletePatch(Patch instance);
    #endregion
		
		public StrassenbilderMetaDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public StrassenbilderMetaDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public StrassenbilderMetaDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public StrassenbilderMetaDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Camera> Cameras
		{
			get
			{
				return this.GetTable<Camera>();
			}
		}
		
		public System.Data.Linq.Table<Polygon> Polygons
		{
			get
			{
				return this.GetTable<Polygon>();
			}
		}
		
		public System.Data.Linq.Table<Image> Images
		{
			get
			{
				return this.GetTable<Image>();
			}
		}
		
		public System.Data.Linq.Table<Patch> Patches
		{
			get
			{
				return this.GetTable<Patch>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Cameras")]
	public partial class Camera : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Name;
		
		private string _Site;
		
		private string _Description;
		
		private string _Comment;
		
		private string _Coordinates;
		
		private System.Nullable<double> _North;
		
		private System.Nullable<double> _East;
		
		private System.Nullable<double> _Elevation;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnSiteChanging(string value);
    partial void OnSiteChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnCommentChanging(string value);
    partial void OnCommentChanged();
    partial void OnCoordinatesChanging(string value);
    partial void OnCoordinatesChanged();
    partial void OnNorthChanging(System.Nullable<double> value);
    partial void OnNorthChanged();
    partial void OnEastChanging(System.Nullable<double> value);
    partial void OnEastChanged();
    partial void OnElevationChanging(System.Nullable<double> value);
    partial void OnElevationChanged();
    #endregion
		
		public Camera()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Site", DbType="NVarChar(50)")]
		public string Site
		{
			get
			{
				return this._Site;
			}
			set
			{
				if ((this._Site != value))
				{
					this.OnSiteChanging(value);
					this.SendPropertyChanging();
					this._Site = value;
					this.SendPropertyChanged("Site");
					this.OnSiteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(50)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comment", DbType="NVarChar(50)")]
		public string Comment
		{
			get
			{
				return this._Comment;
			}
			set
			{
				if ((this._Comment != value))
				{
					this.OnCommentChanging(value);
					this.SendPropertyChanging();
					this._Comment = value;
					this.SendPropertyChanged("Comment");
					this.OnCommentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Coordinates", DbType="NVarChar(50)")]
		public string Coordinates
		{
			get
			{
				return this._Coordinates;
			}
			set
			{
				if ((this._Coordinates != value))
				{
					this.OnCoordinatesChanging(value);
					this.SendPropertyChanging();
					this._Coordinates = value;
					this.SendPropertyChanged("Coordinates");
					this.OnCoordinatesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_North", DbType="Float")]
		public System.Nullable<double> North
		{
			get
			{
				return this._North;
			}
			set
			{
				if ((this._North != value))
				{
					this.OnNorthChanging(value);
					this.SendPropertyChanging();
					this._North = value;
					this.SendPropertyChanged("North");
					this.OnNorthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_East", DbType="Float")]
		public System.Nullable<double> East
		{
			get
			{
				return this._East;
			}
			set
			{
				if ((this._East != value))
				{
					this.OnEastChanging(value);
					this.SendPropertyChanging();
					this._East = value;
					this.SendPropertyChanged("East");
					this.OnEastChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Elevation", DbType="Float")]
		public System.Nullable<double> Elevation
		{
			get
			{
				return this._Elevation;
			}
			set
			{
				if ((this._Elevation != value))
				{
					this.OnElevationChanging(value);
					this.SendPropertyChanging();
					this._Elevation = value;
					this.SendPropertyChanged("Elevation");
					this.OnElevationChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Polygons")]
	public partial class Polygon : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _CameraName;
		
		private string _ImageArea;
		
		private System.Nullable<double> _ImageWidth;
		
		private System.Nullable<double> _ImageHeight;
		
		private string _PolygonPointCollection;
		
		private string _Bitmask;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnCameraNameChanging(string value);
    partial void OnCameraNameChanged();
    partial void OnImageAreaChanging(string value);
    partial void OnImageAreaChanged();
    partial void OnImageWidthChanging(System.Nullable<double> value);
    partial void OnImageWidthChanged();
    partial void OnImageHeightChanging(System.Nullable<double> value);
    partial void OnImageHeightChanged();
    partial void OnPolygonPointCollectionChanging(string value);
    partial void OnPolygonPointCollectionChanged();
    partial void OnBitmaskChanging(string value);
    partial void OnBitmaskChanged();
    #endregion
		
		public Polygon()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CameraName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string CameraName
		{
			get
			{
				return this._CameraName;
			}
			set
			{
				if ((this._CameraName != value))
				{
					this.OnCameraNameChanging(value);
					this.SendPropertyChanging();
					this._CameraName = value;
					this.SendPropertyChanged("CameraName");
					this.OnCameraNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ImageArea", DbType="NVarChar(50)")]
		public string ImageArea
		{
			get
			{
				return this._ImageArea;
			}
			set
			{
				if ((this._ImageArea != value))
				{
					this.OnImageAreaChanging(value);
					this.SendPropertyChanging();
					this._ImageArea = value;
					this.SendPropertyChanged("ImageArea");
					this.OnImageAreaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ImageWidth", DbType="Float")]
		public System.Nullable<double> ImageWidth
		{
			get
			{
				return this._ImageWidth;
			}
			set
			{
				if ((this._ImageWidth != value))
				{
					this.OnImageWidthChanging(value);
					this.SendPropertyChanging();
					this._ImageWidth = value;
					this.SendPropertyChanged("ImageWidth");
					this.OnImageWidthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ImageHeight", DbType="Float")]
		public System.Nullable<double> ImageHeight
		{
			get
			{
				return this._ImageHeight;
			}
			set
			{
				if ((this._ImageHeight != value))
				{
					this.OnImageHeightChanging(value);
					this.SendPropertyChanging();
					this._ImageHeight = value;
					this.SendPropertyChanged("ImageHeight");
					this.OnImageHeightChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PolygonPointCollection", DbType="NVarChar(MAX)")]
		public string PolygonPointCollection
		{
			get
			{
				return this._PolygonPointCollection;
			}
			set
			{
				if ((this._PolygonPointCollection != value))
				{
					this.OnPolygonPointCollectionChanging(value);
					this.SendPropertyChanging();
					this._PolygonPointCollection = value;
					this.SendPropertyChanged("PolygonPointCollection");
					this.OnPolygonPointCollectionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bitmask", DbType="NVarChar(200)")]
		public string Bitmask
		{
			get
			{
				return this._Bitmask;
			}
			set
			{
				if ((this._Bitmask != value))
				{
					this.OnBitmaskChanging(value);
					this.SendPropertyChanging();
					this._Bitmask = value;
					this.SendPropertyChanged("Bitmask");
					this.OnBitmaskChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Images")]
	public partial class Image : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Name;
		
		private string _Place;
		
		private System.DateTime _DateTime;
		
		private string _TimeZone;
		
		private System.Nullable<double> _UnixTime;
		
		private System.Nullable<bool> _Snow;
		
		private System.Nullable<bool> _NoSnow;
		
		private System.Nullable<bool> _Night;
		
		private System.Nullable<bool> _Dusk;
		
		private System.Nullable<bool> _Day;
		
		private System.Nullable<bool> _Foggy;
		
		private System.Nullable<bool> _Cloudy;
		
		private System.Nullable<bool> _Rainy;
		
		private System.Nullable<bool> _BadLighting;
		
		private System.Nullable<bool> _GoodLighting;
		
		private EntityRef<Patch> _Patch;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnPlaceChanging(string value);
    partial void OnPlaceChanged();
    partial void OnDateTimeChanging(System.DateTime value);
    partial void OnDateTimeChanged();
    partial void OnTimeZoneChanging(string value);
    partial void OnTimeZoneChanged();
    partial void OnUnixTimeChanging(System.Nullable<double> value);
    partial void OnUnixTimeChanged();
    partial void OnSnowChanging(System.Nullable<bool> value);
    partial void OnSnowChanged();
    partial void OnNoSnowChanging(System.Nullable<bool> value);
    partial void OnNoSnowChanged();
    partial void OnNightChanging(System.Nullable<bool> value);
    partial void OnNightChanged();
    partial void OnDuskChanging(System.Nullable<bool> value);
    partial void OnDuskChanged();
    partial void OnDayChanging(System.Nullable<bool> value);
    partial void OnDayChanged();
    partial void OnFoggyChanging(System.Nullable<bool> value);
    partial void OnFoggyChanged();
    partial void OnCloudyChanging(System.Nullable<bool> value);
    partial void OnCloudyChanged();
    partial void OnRainyChanging(System.Nullable<bool> value);
    partial void OnRainyChanged();
    partial void OnBadLightingChanging(System.Nullable<bool> value);
    partial void OnBadLightingChanged();
    partial void OnGoodLightingChanging(System.Nullable<bool> value);
    partial void OnGoodLightingChanged();
    #endregion
		
		public Image()
		{
			this._Patch = default(EntityRef<Patch>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Place", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Place
		{
			get
			{
				return this._Place;
			}
			set
			{
				if ((this._Place != value))
				{
					this.OnPlaceChanging(value);
					this.SendPropertyChanging();
					this._Place = value;
					this.SendPropertyChanged("Place");
					this.OnPlaceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateTime", DbType="DateTime NOT NULL")]
		public System.DateTime DateTime
		{
			get
			{
				return this._DateTime;
			}
			set
			{
				if ((this._DateTime != value))
				{
					this.OnDateTimeChanging(value);
					this.SendPropertyChanging();
					this._DateTime = value;
					this.SendPropertyChanged("DateTime");
					this.OnDateTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimeZone", DbType="NVarChar(5)")]
		public string TimeZone
		{
			get
			{
				return this._TimeZone;
			}
			set
			{
				if ((this._TimeZone != value))
				{
					this.OnTimeZoneChanging(value);
					this.SendPropertyChanging();
					this._TimeZone = value;
					this.SendPropertyChanged("TimeZone");
					this.OnTimeZoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UnixTime", DbType="Float")]
		public System.Nullable<double> UnixTime
		{
			get
			{
				return this._UnixTime;
			}
			set
			{
				if ((this._UnixTime != value))
				{
					this.OnUnixTimeChanging(value);
					this.SendPropertyChanging();
					this._UnixTime = value;
					this.SendPropertyChanged("UnixTime");
					this.OnUnixTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Snow", DbType="Bit")]
		public System.Nullable<bool> Snow
		{
			get
			{
				return this._Snow;
			}
			set
			{
				if ((this._Snow != value))
				{
					this.OnSnowChanging(value);
					this.SendPropertyChanging();
					this._Snow = value;
					this.SendPropertyChanged("Snow");
					this.OnSnowChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoSnow", DbType="Bit")]
		public System.Nullable<bool> NoSnow
		{
			get
			{
				return this._NoSnow;
			}
			set
			{
				if ((this._NoSnow != value))
				{
					this.OnNoSnowChanging(value);
					this.SendPropertyChanging();
					this._NoSnow = value;
					this.SendPropertyChanged("NoSnow");
					this.OnNoSnowChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Night", DbType="Bit")]
		public System.Nullable<bool> Night
		{
			get
			{
				return this._Night;
			}
			set
			{
				if ((this._Night != value))
				{
					this.OnNightChanging(value);
					this.SendPropertyChanging();
					this._Night = value;
					this.SendPropertyChanged("Night");
					this.OnNightChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dusk", DbType="Bit")]
		public System.Nullable<bool> Dusk
		{
			get
			{
				return this._Dusk;
			}
			set
			{
				if ((this._Dusk != value))
				{
					this.OnDuskChanging(value);
					this.SendPropertyChanging();
					this._Dusk = value;
					this.SendPropertyChanged("Dusk");
					this.OnDuskChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Day", DbType="Bit")]
		public System.Nullable<bool> Day
		{
			get
			{
				return this._Day;
			}
			set
			{
				if ((this._Day != value))
				{
					this.OnDayChanging(value);
					this.SendPropertyChanging();
					this._Day = value;
					this.SendPropertyChanged("Day");
					this.OnDayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Foggy", DbType="Bit")]
		public System.Nullable<bool> Foggy
		{
			get
			{
				return this._Foggy;
			}
			set
			{
				if ((this._Foggy != value))
				{
					this.OnFoggyChanging(value);
					this.SendPropertyChanging();
					this._Foggy = value;
					this.SendPropertyChanged("Foggy");
					this.OnFoggyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cloudy", DbType="Bit")]
		public System.Nullable<bool> Cloudy
		{
			get
			{
				return this._Cloudy;
			}
			set
			{
				if ((this._Cloudy != value))
				{
					this.OnCloudyChanging(value);
					this.SendPropertyChanging();
					this._Cloudy = value;
					this.SendPropertyChanged("Cloudy");
					this.OnCloudyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rainy", DbType="Bit")]
		public System.Nullable<bool> Rainy
		{
			get
			{
				return this._Rainy;
			}
			set
			{
				if ((this._Rainy != value))
				{
					this.OnRainyChanging(value);
					this.SendPropertyChanging();
					this._Rainy = value;
					this.SendPropertyChanged("Rainy");
					this.OnRainyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BadLighting", DbType="Bit")]
		public System.Nullable<bool> BadLighting
		{
			get
			{
				return this._BadLighting;
			}
			set
			{
				if ((this._BadLighting != value))
				{
					this.OnBadLightingChanging(value);
					this.SendPropertyChanging();
					this._BadLighting = value;
					this.SendPropertyChanged("BadLighting");
					this.OnBadLightingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GoodLighting", DbType="Bit")]
		public System.Nullable<bool> GoodLighting
		{
			get
			{
				return this._GoodLighting;
			}
			set
			{
				if ((this._GoodLighting != value))
				{
					this.OnGoodLightingChanging(value);
					this.SendPropertyChanging();
					this._GoodLighting = value;
					this.SendPropertyChanged("GoodLighting");
					this.OnGoodLightingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Image_Patch", Storage="_Patch", ThisKey="ID", OtherKey="ID", IsUnique=true, IsForeignKey=false)]
		public Patch Patch
		{
			get
			{
				return this._Patch.Entity;
			}
			set
			{
				Patch previousValue = this._Patch.Entity;
				if (((previousValue != value) 
							|| (this._Patch.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Patch.Entity = null;
						previousValue.Image = null;
					}
					this._Patch.Entity = value;
					if ((value != null))
					{
						value.Image = this;
					}
					this.SendPropertyChanged("Patch");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Patches")]
	public partial class Patch : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private int _Image_ID;
		
		private int _Polygon_ID;
		
		private string _BlueHistogram;
		
		private string _GreenHistogram;
		
		private string _RedHistogram;
		
		private System.Nullable<double> _ModeBlue;
		
		private System.Nullable<double> _ModeGreen;
		
		private System.Nullable<double> _ModeRed;
		
		private System.Nullable<double> _MeanBlue;
		
		private System.Nullable<double> _MeanGreen;
		
		private System.Nullable<double> _MeanRed;
		
		private System.Nullable<double> _MedianBlue;
		
		private System.Nullable<double> _MedianGreen;
		
		private System.Nullable<double> _MedianRed;
		
		private System.Nullable<double> _MinimumBlue;
		
		private System.Nullable<double> _MinimumGreen;
		
		private System.Nullable<double> _MinimumRed;
		
		private System.Nullable<double> _MaximumBlue;
		
		private System.Nullable<double> _MaximumGreen;
		
		private System.Nullable<double> _MaximumRed;
		
		private System.Nullable<double> _StandardDeviationBlue;
		
		private System.Nullable<double> _StandardDeviationGreen;
		
		private System.Nullable<double> _StandardDeviationRed;
		
		private System.Nullable<double> _VarianceBlue;
		
		private System.Nullable<double> _VarianceGreen;
		
		private System.Nullable<double> _VarianceRed;
		
		private System.Nullable<double> _ContrastBlue;
		
		private System.Nullable<double> _ContrastGreen;
		
		private System.Nullable<double> _ContrastRed;
		
		private EntityRef<Image> _Image;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnImage_IDChanging(int value);
    partial void OnImage_IDChanged();
    partial void OnPolygon_IDChanging(int value);
    partial void OnPolygon_IDChanged();
    partial void OnBlueHistogramChanging(string value);
    partial void OnBlueHistogramChanged();
    partial void OnGreenHistogramChanging(string value);
    partial void OnGreenHistogramChanged();
    partial void OnRedHistogramChanging(string value);
    partial void OnRedHistogramChanged();
    partial void OnModeBlueChanging(System.Nullable<double> value);
    partial void OnModeBlueChanged();
    partial void OnModeGreenChanging(System.Nullable<double> value);
    partial void OnModeGreenChanged();
    partial void OnModeRedChanging(System.Nullable<double> value);
    partial void OnModeRedChanged();
    partial void OnMeanBlueChanging(System.Nullable<double> value);
    partial void OnMeanBlueChanged();
    partial void OnMeanGreenChanging(System.Nullable<double> value);
    partial void OnMeanGreenChanged();
    partial void OnMeanRedChanging(System.Nullable<double> value);
    partial void OnMeanRedChanged();
    partial void OnMedianBlueChanging(System.Nullable<double> value);
    partial void OnMedianBlueChanged();
    partial void OnMedianGreenChanging(System.Nullable<double> value);
    partial void OnMedianGreenChanged();
    partial void OnMedianRedChanging(System.Nullable<double> value);
    partial void OnMedianRedChanged();
    partial void OnMinimumBlueChanging(System.Nullable<double> value);
    partial void OnMinimumBlueChanged();
    partial void OnMinimumGreenChanging(System.Nullable<double> value);
    partial void OnMinimumGreenChanged();
    partial void OnMinimumRedChanging(System.Nullable<double> value);
    partial void OnMinimumRedChanged();
    partial void OnMaximumBlueChanging(System.Nullable<double> value);
    partial void OnMaximumBlueChanged();
    partial void OnMaximumGreenChanging(System.Nullable<double> value);
    partial void OnMaximumGreenChanged();
    partial void OnMaximumRedChanging(System.Nullable<double> value);
    partial void OnMaximumRedChanged();
    partial void OnStandardDeviationBlueChanging(System.Nullable<double> value);
    partial void OnStandardDeviationBlueChanged();
    partial void OnStandardDeviationGreenChanging(System.Nullable<double> value);
    partial void OnStandardDeviationGreenChanged();
    partial void OnStandardDeviationRedChanging(System.Nullable<double> value);
    partial void OnStandardDeviationRedChanged();
    partial void OnVarianceBlueChanging(System.Nullable<double> value);
    partial void OnVarianceBlueChanged();
    partial void OnVarianceGreenChanging(System.Nullable<double> value);
    partial void OnVarianceGreenChanged();
    partial void OnVarianceRedChanging(System.Nullable<double> value);
    partial void OnVarianceRedChanged();
    partial void OnContrastBlueChanging(System.Nullable<double> value);
    partial void OnContrastBlueChanged();
    partial void OnContrastGreenChanging(System.Nullable<double> value);
    partial void OnContrastGreenChanged();
    partial void OnContrastRedChanging(System.Nullable<double> value);
    partial void OnContrastRedChanged();
    #endregion
		
		public Patch()
		{
			this._Image = default(EntityRef<Image>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					if (this._Image.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Image_ID", DbType="Int NOT NULL")]
		public int Image_ID
		{
			get
			{
				return this._Image_ID;
			}
			set
			{
				if ((this._Image_ID != value))
				{
					this.OnImage_IDChanging(value);
					this.SendPropertyChanging();
					this._Image_ID = value;
					this.SendPropertyChanged("Image_ID");
					this.OnImage_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Polygon_ID", DbType="Int NOT NULL")]
		public int Polygon_ID
		{
			get
			{
				return this._Polygon_ID;
			}
			set
			{
				if ((this._Polygon_ID != value))
				{
					this.OnPolygon_IDChanging(value);
					this.SendPropertyChanging();
					this._Polygon_ID = value;
					this.SendPropertyChanged("Polygon_ID");
					this.OnPolygon_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BlueHistogram", DbType="NVarChar(MAX)")]
		public string BlueHistogram
		{
			get
			{
				return this._BlueHistogram;
			}
			set
			{
				if ((this._BlueHistogram != value))
				{
					this.OnBlueHistogramChanging(value);
					this.SendPropertyChanging();
					this._BlueHistogram = value;
					this.SendPropertyChanged("BlueHistogram");
					this.OnBlueHistogramChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GreenHistogram", DbType="NVarChar(MAX)")]
		public string GreenHistogram
		{
			get
			{
				return this._GreenHistogram;
			}
			set
			{
				if ((this._GreenHistogram != value))
				{
					this.OnGreenHistogramChanging(value);
					this.SendPropertyChanging();
					this._GreenHistogram = value;
					this.SendPropertyChanged("GreenHistogram");
					this.OnGreenHistogramChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RedHistogram", DbType="NVarChar(MAX)")]
		public string RedHistogram
		{
			get
			{
				return this._RedHistogram;
			}
			set
			{
				if ((this._RedHistogram != value))
				{
					this.OnRedHistogramChanging(value);
					this.SendPropertyChanging();
					this._RedHistogram = value;
					this.SendPropertyChanged("RedHistogram");
					this.OnRedHistogramChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModeBlue", DbType="Float")]
		public System.Nullable<double> ModeBlue
		{
			get
			{
				return this._ModeBlue;
			}
			set
			{
				if ((this._ModeBlue != value))
				{
					this.OnModeBlueChanging(value);
					this.SendPropertyChanging();
					this._ModeBlue = value;
					this.SendPropertyChanged("ModeBlue");
					this.OnModeBlueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModeGreen", DbType="Float")]
		public System.Nullable<double> ModeGreen
		{
			get
			{
				return this._ModeGreen;
			}
			set
			{
				if ((this._ModeGreen != value))
				{
					this.OnModeGreenChanging(value);
					this.SendPropertyChanging();
					this._ModeGreen = value;
					this.SendPropertyChanged("ModeGreen");
					this.OnModeGreenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModeRed", DbType="Float")]
		public System.Nullable<double> ModeRed
		{
			get
			{
				return this._ModeRed;
			}
			set
			{
				if ((this._ModeRed != value))
				{
					this.OnModeRedChanging(value);
					this.SendPropertyChanging();
					this._ModeRed = value;
					this.SendPropertyChanged("ModeRed");
					this.OnModeRedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MeanBlue", DbType="Float")]
		public System.Nullable<double> MeanBlue
		{
			get
			{
				return this._MeanBlue;
			}
			set
			{
				if ((this._MeanBlue != value))
				{
					this.OnMeanBlueChanging(value);
					this.SendPropertyChanging();
					this._MeanBlue = value;
					this.SendPropertyChanged("MeanBlue");
					this.OnMeanBlueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MeanGreen", DbType="Float")]
		public System.Nullable<double> MeanGreen
		{
			get
			{
				return this._MeanGreen;
			}
			set
			{
				if ((this._MeanGreen != value))
				{
					this.OnMeanGreenChanging(value);
					this.SendPropertyChanging();
					this._MeanGreen = value;
					this.SendPropertyChanged("MeanGreen");
					this.OnMeanGreenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MeanRed", DbType="Float")]
		public System.Nullable<double> MeanRed
		{
			get
			{
				return this._MeanRed;
			}
			set
			{
				if ((this._MeanRed != value))
				{
					this.OnMeanRedChanging(value);
					this.SendPropertyChanging();
					this._MeanRed = value;
					this.SendPropertyChanged("MeanRed");
					this.OnMeanRedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MedianBlue", DbType="Float")]
		public System.Nullable<double> MedianBlue
		{
			get
			{
				return this._MedianBlue;
			}
			set
			{
				if ((this._MedianBlue != value))
				{
					this.OnMedianBlueChanging(value);
					this.SendPropertyChanging();
					this._MedianBlue = value;
					this.SendPropertyChanged("MedianBlue");
					this.OnMedianBlueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MedianGreen", DbType="Float")]
		public System.Nullable<double> MedianGreen
		{
			get
			{
				return this._MedianGreen;
			}
			set
			{
				if ((this._MedianGreen != value))
				{
					this.OnMedianGreenChanging(value);
					this.SendPropertyChanging();
					this._MedianGreen = value;
					this.SendPropertyChanged("MedianGreen");
					this.OnMedianGreenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MedianRed", DbType="Float")]
		public System.Nullable<double> MedianRed
		{
			get
			{
				return this._MedianRed;
			}
			set
			{
				if ((this._MedianRed != value))
				{
					this.OnMedianRedChanging(value);
					this.SendPropertyChanging();
					this._MedianRed = value;
					this.SendPropertyChanged("MedianRed");
					this.OnMedianRedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MinimumBlue", DbType="Float")]
		public System.Nullable<double> MinimumBlue
		{
			get
			{
				return this._MinimumBlue;
			}
			set
			{
				if ((this._MinimumBlue != value))
				{
					this.OnMinimumBlueChanging(value);
					this.SendPropertyChanging();
					this._MinimumBlue = value;
					this.SendPropertyChanged("MinimumBlue");
					this.OnMinimumBlueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MinimumGreen", DbType="Float")]
		public System.Nullable<double> MinimumGreen
		{
			get
			{
				return this._MinimumGreen;
			}
			set
			{
				if ((this._MinimumGreen != value))
				{
					this.OnMinimumGreenChanging(value);
					this.SendPropertyChanging();
					this._MinimumGreen = value;
					this.SendPropertyChanged("MinimumGreen");
					this.OnMinimumGreenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MinimumRed", DbType="Float")]
		public System.Nullable<double> MinimumRed
		{
			get
			{
				return this._MinimumRed;
			}
			set
			{
				if ((this._MinimumRed != value))
				{
					this.OnMinimumRedChanging(value);
					this.SendPropertyChanging();
					this._MinimumRed = value;
					this.SendPropertyChanged("MinimumRed");
					this.OnMinimumRedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaximumBlue", DbType="Float")]
		public System.Nullable<double> MaximumBlue
		{
			get
			{
				return this._MaximumBlue;
			}
			set
			{
				if ((this._MaximumBlue != value))
				{
					this.OnMaximumBlueChanging(value);
					this.SendPropertyChanging();
					this._MaximumBlue = value;
					this.SendPropertyChanged("MaximumBlue");
					this.OnMaximumBlueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaximumGreen", DbType="Float")]
		public System.Nullable<double> MaximumGreen
		{
			get
			{
				return this._MaximumGreen;
			}
			set
			{
				if ((this._MaximumGreen != value))
				{
					this.OnMaximumGreenChanging(value);
					this.SendPropertyChanging();
					this._MaximumGreen = value;
					this.SendPropertyChanged("MaximumGreen");
					this.OnMaximumGreenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaximumRed", DbType="Float")]
		public System.Nullable<double> MaximumRed
		{
			get
			{
				return this._MaximumRed;
			}
			set
			{
				if ((this._MaximumRed != value))
				{
					this.OnMaximumRedChanging(value);
					this.SendPropertyChanging();
					this._MaximumRed = value;
					this.SendPropertyChanged("MaximumRed");
					this.OnMaximumRedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StandardDeviationBlue", DbType="Float")]
		public System.Nullable<double> StandardDeviationBlue
		{
			get
			{
				return this._StandardDeviationBlue;
			}
			set
			{
				if ((this._StandardDeviationBlue != value))
				{
					this.OnStandardDeviationBlueChanging(value);
					this.SendPropertyChanging();
					this._StandardDeviationBlue = value;
					this.SendPropertyChanged("StandardDeviationBlue");
					this.OnStandardDeviationBlueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StandardDeviationGreen", DbType="Float")]
		public System.Nullable<double> StandardDeviationGreen
		{
			get
			{
				return this._StandardDeviationGreen;
			}
			set
			{
				if ((this._StandardDeviationGreen != value))
				{
					this.OnStandardDeviationGreenChanging(value);
					this.SendPropertyChanging();
					this._StandardDeviationGreen = value;
					this.SendPropertyChanged("StandardDeviationGreen");
					this.OnStandardDeviationGreenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StandardDeviationRed", DbType="Float")]
		public System.Nullable<double> StandardDeviationRed
		{
			get
			{
				return this._StandardDeviationRed;
			}
			set
			{
				if ((this._StandardDeviationRed != value))
				{
					this.OnStandardDeviationRedChanging(value);
					this.SendPropertyChanging();
					this._StandardDeviationRed = value;
					this.SendPropertyChanged("StandardDeviationRed");
					this.OnStandardDeviationRedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VarianceBlue", DbType="Float")]
		public System.Nullable<double> VarianceBlue
		{
			get
			{
				return this._VarianceBlue;
			}
			set
			{
				if ((this._VarianceBlue != value))
				{
					this.OnVarianceBlueChanging(value);
					this.SendPropertyChanging();
					this._VarianceBlue = value;
					this.SendPropertyChanged("VarianceBlue");
					this.OnVarianceBlueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VarianceGreen", DbType="Float")]
		public System.Nullable<double> VarianceGreen
		{
			get
			{
				return this._VarianceGreen;
			}
			set
			{
				if ((this._VarianceGreen != value))
				{
					this.OnVarianceGreenChanging(value);
					this.SendPropertyChanging();
					this._VarianceGreen = value;
					this.SendPropertyChanged("VarianceGreen");
					this.OnVarianceGreenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VarianceRed", DbType="Float")]
		public System.Nullable<double> VarianceRed
		{
			get
			{
				return this._VarianceRed;
			}
			set
			{
				if ((this._VarianceRed != value))
				{
					this.OnVarianceRedChanging(value);
					this.SendPropertyChanging();
					this._VarianceRed = value;
					this.SendPropertyChanged("VarianceRed");
					this.OnVarianceRedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContrastBlue", DbType="Float")]
		public System.Nullable<double> ContrastBlue
		{
			get
			{
				return this._ContrastBlue;
			}
			set
			{
				if ((this._ContrastBlue != value))
				{
					this.OnContrastBlueChanging(value);
					this.SendPropertyChanging();
					this._ContrastBlue = value;
					this.SendPropertyChanged("ContrastBlue");
					this.OnContrastBlueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContrastGreen", DbType="Float")]
		public System.Nullable<double> ContrastGreen
		{
			get
			{
				return this._ContrastGreen;
			}
			set
			{
				if ((this._ContrastGreen != value))
				{
					this.OnContrastGreenChanging(value);
					this.SendPropertyChanging();
					this._ContrastGreen = value;
					this.SendPropertyChanged("ContrastGreen");
					this.OnContrastGreenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContrastRed", DbType="Float")]
		public System.Nullable<double> ContrastRed
		{
			get
			{
				return this._ContrastRed;
			}
			set
			{
				if ((this._ContrastRed != value))
				{
					this.OnContrastRedChanging(value);
					this.SendPropertyChanging();
					this._ContrastRed = value;
					this.SendPropertyChanged("ContrastRed");
					this.OnContrastRedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Image_Patch", Storage="_Image", ThisKey="ID", OtherKey="ID", IsForeignKey=true)]
		public Image Image
		{
			get
			{
				return this._Image.Entity;
			}
			set
			{
				Image previousValue = this._Image.Entity;
				if (((previousValue != value) 
							|| (this._Image.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Image.Entity = null;
						previousValue.Patch = null;
					}
					this._Image.Entity = value;
					if ((value != null))
					{
						value.Patch = this;
						this._ID = value.ID;
					}
					else
					{
						this._ID = default(int);
					}
					this.SendPropertyChanged("Image");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
